# The Spaghetti Code Challenge

## Background

The goal of this challenge is to replicate Figure 3 of Schaefer et al. 2000, as shown in README.md.

## Data

Figure 3 of Schaefer et al. 2000, visuallizes stream contents from four different sites: three sites around Quebrada Cuenca and one in Rio Meyes, Puente Roto.

To process each the data from each site, I created a function called "moving-average". This function takes the mean concentration of each ion of interest (Nitrate(NO3-N), Ammonium (NH4-N), Potassium (K), Magnesium (Mg), and Calcium (Ca)) at the site every nine weeks thoughout the sampling period. The function subsequently generates new datasets that start with "mov-avg" containing the nine-week average.

To visuallize data from all four streams at the same time, I bind the datasets together and pivot the columns. This allows me to plot concentration over time for each ion of interest.

## Results

\[Insert results\]

```{r}
library(tidyverse)
all_streams_conc <- read_csv(
  "/Users/kellyanne/Desktop/meds2027/eds214/kmo214final/output/clean_data.csv"
)

hurricane_date <- as.Date("1989-09-18")

ggplot(
  data = all_streams_conc,
  mapping = aes(
    x = window_start,
    y = Concentration,
    linetype = Sample_ID
  )
) +
  geom_line() +
  geom_vline(
    xintercept = hurricane_date,
    linetype = "dashed",
    linewidth = 0.4
  ) +
  theme_classic() +
  labs(
    title = "Ion Concentration over Time",
    x = "Years",
    y = "Concentration (mg/l)"
  ) +
  facet_wrap(~Ions, nrow = 5, ncol = 1, scales = "free")
```